### PR TITLE
added product popularity code/replaces Bin's previous version

### PR DESCRIPTION
**Pull request by tayloraharry**
## Description
added popularity code to application
## Related to Issue Number
ts of the application that this PR will affect:

### CODE REVIEW

**Comment by DevDreed** [comment]
So it appears you took out the getAllProducts method.  This would have been used to build the products screen when adding items to the cart.  Was that your intention?  Are we planning to do that differently?

**Comment by tayloraharry** [comment]
@drdreed i must of misunderstood, the method call was under menu item 6 on the program (the popularity option) so we should probably un comment that out and add the correct call to 4 and keep my changes at 6...haha does that make any sense?

**Comment by DevDreed** [comment]
Yeah that was my fault I was just testing my functionality.  I guess I shouldn't have chose 6 as the menu option.  My bad.

**Comment by tayloraharry** [comment]
no worries, i just got confused and should of asked about that method,
thanks sir

**Comment by LibE4** [comment]
👍

**Pull request merged**
